Adding UBI-8 JDK-21 image
paketo-community/ubi-base-stack pull request #41
Opened 2024-02-02 13:07 UTC by matzew

## Summary

Adding JDK-21 ubi image (see #40)

## Use Cases

New LTS version of java is 21, and we do not yet have that in this repo 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2024-02-02 17:23 UTC, pacostas commented
LGTM

2024-02-02 17:45 UTC, pacostas commented
@sophiewigmore Can you LGTM ?

2024-02-06 22:26 UTC, sophiewigmore approved these changes

2024-02-07 11:10 UTC, pacostas requested changes
@matzew Can you also add on .gitignore below line, to exclude the build artifacts from git changes?
`build-java-21/`

By comiting these changes, the tests pass.

2024-02-07 11:10 UTC, pacostas commented on metadata_test.go
> +			archive, err := os.Open(stack.RunJava17Archive)
```suggestion
			archive, err := os.Open(stack.RunJava21Archive)
```

2024-02-07 11:10 UTC, pacostas commented on metadata_test.go
> +			runReleaseDateJava17, err := time.Parse(time.RFC3339, file.Config.Labels["io.buildpacks.stack.released"])
```suggestion
			runReleaseDateJava21, err := time.Parse(time.RFC3339, file.Config.Labels["io.buildpacks.stack.released"])
```

2024-02-07 11:10 UTC, pacostas commented on metadata_test.go
> +			Expect(runReleaseDateJava17).NotTo(BeZero())
```suggestion
			Expect(runReleaseDateJava21).NotTo(BeZero())
```

2024-02-07 13:43 UTC, pacostas approved these changes
LGTM

2024-02-07 22:04 UTC, sophiewigmore approved these changes

2024-02-09 13:36 UTC, matzew commented
@sophiewigmore thanks for approving the PR. Do you think we can merge the PR? 

Once merged / image published, I will update the [ubi-java-extension](https://github.com/paketo-community/ubi-java-extension) repo for leveraging this work here.

2024-02-14 20:46 UTC, mhdawson approved these changes
LGTM

2024-02-26 11:48 UTC, pacostas commented
@mhdawson this is the next one we need to merge . Also after merging can you close this issue https://github.com/paketo-community/ubi-base-stack/issues/40 ?

2024-02-26 16:58 UTC, merged